name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  python-package:
    name: Test build/install on Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install build tools and linters
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      - name: Run ruff (formatting and linting)
        run: |
          ruff check .
          ruff format --check .

      - name: Test install
        run: |
          pip install .

      - name: Run tests
        run: |
          PYTHONPATH=. pytest

  docker-build:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build Docker image
        run: |
          docker build .
